name: GH-ACTION-DOCKER-COMPOSE-BUILD-IMAGE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  GH-ACTION-INSTALL-DOCKER-COMPOSE:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest docker-compose
        uses: TheKitoInc/gh-action-install-docker-compose@main

      - name: Check docker-compose version
        run: docker-compose --version
