name: GH-ACTION-DOCKER-COMPOSE-BUILD-IMAGE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  GH-ACTION-DOCKER-COMPOSE-BUILD-IMAGE:
    runs-on: ubuntu-latest

    steps:
      - name: Upgrade docker-compose
        uses: TheKitoInc/gh-action-install-docker-compose@main
