name: GH-ACTION-DOCKER-COMPOSE-INSTALL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  GH-ACTION-DOCKER-COMPOSE-INSTALL:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest docker-compose
        uses: TheKitoInc/gh-action-docker-compose-install@main
